# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [2]:
# Let's import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [3]:
# Lets create a Python list. 
my_list = [-1,0,1] 

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [5]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix_one.shape

(2, 3)

In [8]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array

array([-1,  0,  1])

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [9]:
num = np.arange(100) # similar to range() in Python, not including 100  
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [11]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [12]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 50, 100, retstep=True)

(array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
         3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
         5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
         8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
        10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
        13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
        15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
        18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
        20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
        23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
        25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
        28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
        30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
        33.17171717, 33.66666667, 34.16161616, 34.6

In [13]:
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 np.float64(0.3157894736842105))

In [14]:
np.linspace(1,2,30) # 1-D array 

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [15]:
x = np.arange(0, 16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
x.shape

(16,)

In [17]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
y = x.reshape(2, 2, 4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
y.shape

(2, 2, 4)

In [20]:
x = y.reshape(16,)

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
x.shape

(16,)

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [30]:
np.random.rand(4) # 1-D array with three elements

array([0.94929628, 0.72688665, 0.2798212 , 0.83228422])

In [34]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.61657769, 0.66201745, 0.78706286, 0.51378684],
       [0.3513169 , 0.81342779, 0.79624487, 0.84477103],
       [0.475097  , 0.60454542, 0.16318112, 0.51893866],
       [0.00522162, 0.98552795, 0.86625218, 0.8238466 ],
       [0.22882161, 0.40681524, 0.32208029, 0.1666044 ],
       [0.77273794, 0.46972152, 0.45622336, 0.94858783]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [35]:
np.random.randn(20, 5)

array([[ 4.59288253e-01, -1.37169244e+00,  2.96748111e-01,
        -1.70219807e-01,  4.87170611e-01],
       [-7.58520895e-01, -4.54477373e-01,  3.86408203e-01,
         8.43426367e-01,  5.64885439e-01],
       [-1.12484964e+00,  2.84752397e-01, -1.39630920e-01,
         1.42151978e-01,  9.92444840e-01],
       [ 1.03202743e+00, -4.38977387e-01, -7.20101396e-01,
         2.25739794e-01, -1.13154585e+00],
       [ 8.32842498e-01, -3.45213081e-01,  2.91281340e-02,
         7.33095011e-01, -1.27737978e+00],
       [ 1.06468997e+00, -5.51681334e-01, -9.66912722e-01,
        -1.65798651e+00, -3.86616787e-01],
       [-2.57152064e+00, -1.50667398e+00,  1.01358939e+00,
        -7.27829505e-02, -3.16954648e-01],
       [ 6.72081312e-01, -5.03237787e-02, -1.81985673e+00,
        -2.12358258e-01,  1.54106630e-03],
       [-8.17841646e-01,  1.27900051e+00, -3.15976506e-01,
        -1.39805412e+00, -4.22664697e-01],
       [-3.16098626e-01,  1.24874509e-01, -4.47213711e-01,
        -1.69865280e+00

In [36]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

array([[-9.60001036e-01],
       [ 1.55862402e+00],
       [-1.17663944e+00],
       [-4.96256856e-01],
       [ 2.13660749e+00],
       [-1.57201338e-01],
       [ 8.70493134e-01],
       [-4.87848046e-01],
       [ 2.00392617e+00],
       [-2.74898263e-01],
       [ 2.62989644e-02],
       [ 7.18126325e-03],
       [ 2.33801824e-01],
       [-1.00573777e+00],
       [-1.78502508e+00],
       [-1.38962418e+00],
       [ 8.02578392e-01],
       [ 1.03708459e+00],
       [ 1.10415298e+00],
       [ 4.47309942e-01],
       [-6.81299699e-01],
       [ 6.78735431e-01],
       [-9.75869220e-01],
       [-9.64030754e-01],
       [ 8.20556881e-01],
       [ 1.10750188e+00],
       [ 2.16477668e-01],
       [ 1.33827831e+00],
       [-1.07480629e+00],
       [-2.21344378e+00],
       [-1.35033300e+00],
       [ 7.93607051e-02],
       [ 8.23601398e-01],
       [-6.58628054e-01],
       [-6.99713748e-01],
       [-9.64772453e-01],
       [ 8.81196758e-01],
       [-5.05194785e-01],
       [-2.3

In [27]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

A
0    1.321226
1    0.371333
2   -0.919075
3   -1.399728
4   -0.582049
..        ...
995 -1.450967
996 -0.534443
997  0.092925
998 -0.035656
999 -0.221482

[1000 rows x 1 columns]

In [44]:
df['A'].hist(bins=30)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [40]:
np.random.randint(1, 50, 5) #returns one random int, 1 inclusive, 200 exclusive

array([45,  5, 20, 26, 49], dtype=int32)

In [41]:
np.random.randint(100,200,20).reshape(4,5) #returns ten random int,

array([[142, 166, 135, 155, 106],
       [165, 149, 101, 181, 166],
       [177, 158, 115, 152, 146],
       [150, 142, 171, 126, 102]], dtype=int32)

In [45]:
arr0 = np.random.randint(low=1000, high=2000, size=[5,8])
arr0

array([[1787, 1347, 1901, 1340, 1164, 1778, 1356, 1202],
       [1942, 1970, 1752, 1848, 1422, 1684, 1711, 1603],
       [1096, 1802, 1113, 1646, 1616, 1973, 1426, 1467],
       [1132, 1254, 1674, 1908, 1937, 1152, 1355, 1715],
       [1408, 1689, 1795, 1780, 1209, 1206, 1434, 1077]], dtype=int32)

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [46]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [47]:
array_ranint

array([31, 91, 27, 50, 49, 75, 42, 90, 19, 38], dtype=int32)

#### `max()` & `min()`
Useful methods for finding max or min values.

In [48]:
array_ranint.min()

np.int32(19)

In [49]:
array_ranint.max()

np.int32(91)

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [50]:
array_ranint.argmax() # index starts from 0

np.int64(1)

In [51]:
array_ranint.argmin()

np.int64(8)

### Attributes
* `size, shape, dtype` 

In [52]:
array_arange=np.arange(16)

In [53]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
array_arange.shape

(16,)

In [55]:
array_arange.size

16

In [56]:
# Size of the array 
array_arange.itemsize

8

In [57]:
# Type of the data.
array_arange.dtype

dtype('int64')

In [58]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
array_arange.shape = (4,4)

In [62]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [64]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
array_arange.reshape(1,16).shape

(1, 16)

In [67]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Indexing & slicing of 1-D arrays (vectors)

In [69]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [70]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [71]:
array_1d[2]

np.int64(0)

In [72]:
# Getting a range value
array_1d[0:3]

array([-10,  -2,   0])

In [73]:
# Using -ve index 
array_1d[-2]

np.int64(106)

In [74]:
# Using -ve index for a range 
array_1d[1:-2]

array([-2,  0,  2, 17])

In [75]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [76]:
array_1d[:2]

array([-10,  -2])

In [77]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [78]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [79]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [80]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [81]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [ ]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [ ]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
# another way 
row = 5
column = 2
array_2d[row, column]

np.int64(22)

In [84]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

np.int64(22)

In [85]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
# 2D array slicing
array_2d[:2,:2] 

array([[0, 1],
       [4, 5]])

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [ ]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [ ]:
array_1d[0:5] = 500 
array_1d

In [ ]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

In [ ]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

In [ ]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d * np.arange(0,4)

In [ ]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d[[3, 1]]

In [ ]:
array_2d[:,[2]]

In [ ]:
array_2d

In [ ]:
# We can use any order
array_2d[[3, 1]]

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

In [ ]:
# grabbing rows
array_2d[[2,3]] #[2][3]

In [ ]:
array_2d[:3, [2,3]]

In [ ]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

In [ ]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

We can apply condition such as >, <, == etc

In [ ]:
array_1d > 3

In [ ]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

Lets create a mask to **filter out the even numbers in "array_1d"**

In [ ]:
array_1d % 2

In [ ]:
0 == array_1d % 2

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

In [ ]:
array_1d

In [ ]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [ ]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

In [ ]:
# Subtracting two arrays
arr - arr

In [ ]:
# Multiplication
arr * arr

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

In [ ]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

In [ ]:
# Power of all the elements in an array
arr ** 2

In [ ]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [ ]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

In [ ]:
# max and min values
np.max(arr), np.min(arr)

In [ ]:
arr.max()

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

**Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d.sum()

In [ ]:
array_2d.sum(axis=1)

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d.std()

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d

In [ ]:
array_2d % 3 == 0

In [ ]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

NameError: name 'array_2d' is not defined

In [ ]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])