# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

Vectors are one dimensional arrays. where matrices are multidimensional arrays.

**2. How to import `NumPy` library?** 

In [1]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [5]:
list_1 = [1, 2, 3, 4, 5]
array_1 = np.array(list_1)

print(array_1)
print(array_1.dtype)

[1 2 3 4 5]
int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [ ]:
array = np.arange(6)
print(array)

[0 1 2 3 4 5]


**5. Generate an `array of "5" zeros`**

In [ ]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


**6. Generate the following `matrix`.**

In [ ]:
matrix = np.zeros((3, 4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [ ]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [ ]:
tens_array = np.full(5, 10)
print(tens_array)

[10 10 10 10 10]


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [14]:
even_numbers = np.arange(51, 100, 2)
print(even_numbers)

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [15]:
np.linspace(0, 1, 10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [17]:
vector = np.arange(25)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
matrix = vector.reshape(5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

The lines of code directly reshapes the vector into a 5x5 matrix using the reshape() method.

In [22]:
matrix.shape = (5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [23]:
array = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(array)

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]]


**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [24]:
array = np.linspace(0, 24, 25).reshape(5, 5)
print(array)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


**14. What is the main difference between `linspace()` and `arange()`?**

linspace generates evenly spaced numbers over a specified interval, while arange generates numbers with a fixed step size.

**15. How to generate a single random integer number using NumPy built-in function?**

In [26]:
random_integer = np.random.randint(10) 
print(random_integer)

4


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [27]:
random_matrix = np.random.rand(7, 5)
print(random_matrix)

[[0.8617269  0.09137853 0.1866475  0.9880716  0.2361315 ]
 [0.45335211 0.64583462 0.79062926 0.32234262 0.56699793]
 [0.17485226 0.64751066 0.34841784 0.442532   0.82321148]
 [0.94046049 0.42589382 0.45581842 0.77272249 0.78618503]
 [0.99032649 0.31675982 0.58099452 0.91511079 0.76037276]
 [0.73055341 0.34095521 0.22355868 0.05053828 0.25091194]
 [0.84624891 0.67839125 0.05629152 0.57071114 0.16532925]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [28]:
diagonal_matrix = np.diag([5] * 5)
print(diagonal_matrix)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]
